### ISSUE TITLE
Unable to satisfy the following requirements: AFNetworking (~> 2.5)

### ISSUE THREAD

**Issue by jeanmartin** [clayallsopp/afmotion#92]
This might be an issue on my machine but this is what happens:
````
# motion --version
3.12
````
I create a new rubymotion iOS app and add to my Gemfile:
````
gem 'motion-cocoapods'
gem 'afmotion'
````
so
````
# bundle list
Gems included by the bundle:
  * activesupport (4.2.1)
  * bundler (1.7.6)
  * claide (0.8.1)
  * cocoapods (0.37.2)
  * cocoapods-core (0.37.2)
  * cocoapods-downloader (0.9.0)
  * cocoapods-plugins (0.4.2)
  * cocoapods-trunk (0.6.1)
  * cocoapods-try (0.4.5)
  * colored (1.2)
  * escape (0.0.4)
  * fuzzy_match (2.0.4)
  * i18n (0.7.0)
  * json (1.8.1)
  * minitest (5.4.3)
  * molinillo (0.2.3)
  * motion-cocoapods (1.7.1)
  * nap (0.8.0)
  * netrc (0.7.8)
  * rake (10.4.2)
  * thread_safe (0.3.5)
  * tzinfo (1.2.2)
  * xcodeproj (0.24.2)
````

Running rake pod:install now has this result:
````
# rake pod:install
Updating spec repo `master`
Analyzing dependencies
rake aborted!
Pod::Informative: [!] Unable to satisfy the following requirements:

- `AFNetworking (~> 2.5)` required by `Podfile`/Users/me/.rvm/gems/ruby-2.0.0-p598@gemset/gems/cocoapods-0.37.2/lib/cocoapods/resolver.rb:395:in `handle_resolver_error'
/Users/me/.rvm/gems/ruby-2.0.0-p598@gemset/gems/cocoapods-0.37.2/lib/cocoapods/resolver.rb:64:in `rescue in resolve'
/Users/me/.rvm/gems/ruby-2.0.0-p598@gemset/gems/cocoapods-0.37.2/lib/cocoapods/resolver.rb:55:in `resolve'
/Users/me/.rvm/gems/ruby-2.0.0-p598@gemset/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:440:in `block in resolve_dependencies'
/Users/me/.rvm/gems/ruby-2.0.0-p598@gemset/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/me/.rvm/gems/ruby-2.0.0-p598@gemset/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:438:in `resolve_dependencies'
/Users/me/.rvm/gems/ruby-2.0.0-p598@gemset/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:63:in `analyze'
/Users/me/.rvm/gems/ruby-2.0.0-p598@gemset/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:196:in `analyze'
/Users/me/.rvm/gems/ruby-2.0.0-p598@gemset/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:114:in `block in resolve_dependencies'
/Users/me/.rvm/gems/ruby-2.0.0-p598@gemset/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/me/.rvm/gems/ruby-2.0.0-p598@gemset/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:113:in `resolve_dependencies'
/Users/me/.rvm/gems/ruby-2.0.0-p598@gemset/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:93:in `install!'
/Users/me/.rvm/gems/ruby-2.0.0-p598@gemset/gems/motion-cocoapods-1.7.1/lib/motion/project/cocoapods.rb:238:in `install!'
/Users/me/.rvm/gems/ruby-2.0.0-p598@gemset/gems/motion-cocoapods-1.7.1/lib/motion/project/cocoapods.rb:361:in `block (2 levels) in <top (required)>'
/Users/me/.rvm/gems/ruby-2.0.0-p598@gemset/bin/ruby_executable_hooks:15:in `eval'
/Users/me/.rvm/gems/ruby-2.0.0-p598@gemset/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => pod:install
(See full trace by running task with --trace)
````

**Comment by jeanmartin** [comment]
Removing the afmotion gem and adding
````
app.pods do
  pod 'AFNetworking'
end
````
to my Rakefile works:
````
# rake pod:install
Updating spec repo `master`
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (2.0.3)
Generating Pods project
````
It seems it does not know about AFNetworking > 2.0.3 ?!

**Comment by jeanmartin** [comment]
ok, solved it. Yes, it was an issue on my machine:
````
$ pod repo update --verbose

Updating spec repo `master`
  $ /usr/local/bin/git pull --ff-only
  fatal: Not possible to fast-forward, aborting.

[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`
````
This fixed it:
````
$ pod repo remove master
Removing spec repo `master`
$ pod setup
Setting up CocoaPods master repo
Setup completed
````
